name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .

  deploy-supabase:
    runs-on: ubuntu-latest
    needs: build-and-deploy-frontend
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.158.0
      - name: Initialize Supabase
        run: supabase init
      - name: Login to Supabase
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN" --no-browser
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Set Supabase token
        run: echo "Token ready"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Link project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      - name: Deploy Edge Functions
        run: |
          supabase functions deploy plan_trip
          supabase functions deploy chat_guide
          supabase functions deploy reschedule 